name: 'CI/CD'

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: $REGISTRY/${{ github.repository }}
  IMAGE_TAG_WITH_SHA: $IMAGE_NAME:$GITHUB_SHA

jobs:
  check-build-deploy:
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: |
          ~/.npm
          ~/.pnpm-store
        key: build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          build-${{ env.cache-name }}-
          build-

    - name: Install dependencies
      run: |
        npm install --global pnpm
        cd ./frontend/
        pnpm install --frozen-lockfile
        cd ../backend/
        pnpm install --frozen-lockfile

    # - name: lint FIXME add eslint
    #   run: npm run lint

    - name: Unit test
      run: |
        cd ./frontend/
        pnpm test

    # FIXME test and lint backend

    - name: Build frontend
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
      run: |
        cd ./frontend/
        pnpm build

    - name: Deploy frontend
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
      # FIXME what about deploying to GH pages?
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      run: |
        cd frontend/build/
        branchName=${GITHUB_REF##*/}
        bucket=${AWS_S3_BUCKET:?}
        if [ $branchName = 'develop' ]; then
          bucket="dev-${bucket}"
        fi
        aws s3 sync --delete . s3://${bucket}

    - name: Build and push backend Docker image
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
      env:
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo $DOCKER_PASSWORD | docker login --password-stdin \
          --username $DOCKER_USERNAME $REGISTRY
        cd backend/
        branchName=${GITHUB_REF##*/}
        /usr/bin/docker buildx build \
          --tag $IMAGE_TAG_WITH_SHA \
          --tag $IMAGE_NAME:$branchName \
          --push \
          .

    - name: Deploy backend
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
      env:
        # FIXME get gcp auth
        GCP_SERVICE_NAME: ${{ secrets.GCP_SERVICE_NAME }}
        GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
        GOOGLE_COMPUTE_ZONE: 'us-west1'
      run: |
        commonParams="--platform managed --region ${GOOGLE_COMPUTE_ZONE:?}"
        gcloud beta run deploy ${GCP_SERVICE_NAME:?} \
          --image ${IMAGE_TAG_WITH_SHA:?} \
          --execution-environment gen2 \
          $commonParams \
          --allow-unauthenticated \
          --max-instances=1 \
          --set-env-vars \
            GCS_BUCKET=${GCS_BUCKET:?}
        gcloud beta run services describe \
          $GCP_SERVICE_NAME \
          $commonParams \
          --format="value(status.address.url)"
