name: 'CI/CD'

on: push

jobs:
  check-build-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    # ubuntu-latest already comes with node installed
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md#package-management

    # FIXME consider caching deps
    # https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows

    - name: Install dependencies
      run: |
        cd ./frontend/
        npm ci

    # - name: lint FIXME add eslint
    #   run: npm run lint

    - name: unit test
      run: |
        cd ./frontend/
        npm run test

    - name: build
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
      run: |
        cd ./frontend/
        npm run build

    # ubuntu-latest already comes with aws-cli
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md#cli-tools
    - name: deploy
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      run: |
        cd frontend/build/
        branchName=${GITHUB_REF##*/}
        bucket=${AWS_S3_BUCKET:?}
        if [ $branchName = 'develop' ]; then
          bucket="dev-${bucket}"
        fi
        aws s3 sync --delete . s3://${bucket}
