name: Continuous Integration

on: push

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    # ubuntu-latest already comes with node installed
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md#package-management

    # FIXME consider caching deps
    # https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows

    - name: Install dependencies
      run: |
        cd ./frontend/
        npm ci

    # - name: lint FIXME add eslint
    #   run: npm run lint

    - name: unit test
      run: |
        cd ./frontend/
        npm run test
